package teamhardcoder.y_fi.database.data;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

/**
 * Created by Andrew on 2/13/17.
 */

@DynamoDBTable(tableName = "GROUP_EXPENSE")
public class GroupExpense {

    private String expenseId; // Autogenerated when creating object
    private String createdDate; // Autogenerated when creating object
    private String groupId;
    private double amount;
    private String description;
    private String categoryName;

    public GroupExpense() {
        Calendar cur_cal = Calendar.getInstance();
        Date dt = cur_cal.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
        //dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        createdDate = dateFormat.format(dt);

    }

    public GroupExpense(String groupId, double amount, String description, String categoryName){
        this();
        this.groupId = groupId;
        this.amount = amount;
        this.description = description;
        this.categoryName = categoryName;
    }

    @DynamoDBHashKey(attributeName = "expenseId")
    @DynamoDBAutoGeneratedKey
    public String getExpenseId() {
        return expenseId;
    }

    /*
     * DON'T CALL THIS METHOD
     */
    public void setExpenseId(String expenseId) {
        this.expenseId = expenseId;
    }

    @DynamoDBAttribute(attributeName = "createdDate")
    public String getCreatedDate() {
        return createdDate;
    }

    /*
     * DON'T CALL THIS METHOD
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAttribute(attributeName = "groupId")
    public String getGroupId() {
        return groupId;
    }
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @DynamoDBAttribute(attributeName = "amount")
    public double getAmount() {
        return amount;
    }
    public void setAmount(double amount) {
        this.amount = amount;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "categoryName")
    public String getCategoryName() {
        return categoryName;
    }
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Override
    public String toString() {
        return "GroupExpense{" +
                "expenseId=" + expenseId +
                ", createdDate='" + createdDate +
                ", groupId=" +  groupId+
                ", amount=" + amount +
                ", description=" + description+
                ", categoryName=" +categoryName +
                "}";
    }

}
