package teamhardcoder.y_fi.database.data;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

/**
 * Created by Andrew on 2/13/17.
 */

@DynamoDBTable(tableName = "MESSAGE")
public class Message {

    private String messageId; // Autogenerated when creating object
    private String createdDate; // Autogenerated when creating object
    private String groupId;
    private String userId;
    private String content;

    public Message() {
        Calendar cur_cal = Calendar.getInstance();
        Date dt = cur_cal.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
        //dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        createdDate = dateFormat.format(dt);
    }

    public Message(String groupId, String userId, String content){
        this();
        this.groupId = groupId;
        this.userId = userId;
        this.content = content;
    }

    @DynamoDBHashKey(attributeName = "messageId")
    @DynamoDBAutoGeneratedKey
    public String getMessageId() {
        return messageId;
    }

    /*
     * DON'T CALL THIS METHOD
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    @DynamoDBAttribute(attributeName = "createdDate")
    public String getCreatedDate() {
        return createdDate;
    }

    /*
     * DON'T CALL THIS METHOD
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAttribute(attributeName = "groupId")
    public String getGroupId() {
        return groupId;
    }
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "content")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return "Message{" +
                "messageId=" + messageId +
                ", createdDate=" + createdDate +
                ", groupId=" + groupId +
                ", userId=" + userId +
                ", content=" + content +
                "}";
    }
}
